openapi: 3.0.0
info:
    description: Mock API for vue-typescript-admin-template.
    version: 1.0.0
    title: Mock API
    contact:
        email: armourcy@email.com
    license:
        name: MIT
        url: https://opensource.org/licenses/MIT
servers:
    - url: /mock-api/v1
paths:
    /login:
        post:
            operationId: login
    /login-info:
        post:
            operationId: getLoginInfo
    /auth-list:
        post:
            operationId: getAuthList
    /getSelectLists:
        post:
            operationId: getSelectLists
    /articles:
        get:
            operationId: getArticles
